export const PAGE_INTROS: Record<string, string> = {
  "badge": "Badge ported 1:1 from the original tokens export (badges.json, pella.comp.badge.*): numbered pills with caption labels plus simple markers that carry no label leaves at all. Fills resolve to theme-fixed system colors per state - light, red, yellow and green; disabled layers opacity.disabled over every variant.",
  "checkbox": "Checkbox control ported 1:1 from the original tokens export (checkboxes.json, brand family). The checked box is a solid brand-family fill with a graySoft check glyph.",
  "color-roles": "Every base color of the system for each theme: brand primary, traffic lights (red - error, yellow - alert, green - success), and the five-step gray scale. Each value lists its lighter and darker variants derived with a transparent layer at 32% over the base color - white to lighten, black to darken. That is how interactive states such as hover shift each base value instead of switching to fixed colors.",
  "field": "Text field ported 1:1 from the original tokens export (fields.json): floating-label input in two tone compositions - solid fill and outlined box - across small and large sizes, each carrying resting, error and disabled leaves; resolved colors come straight from themes/light.json.",
  "pagination": "Pagination ported from the original tokens export (paginations.json, simple.brand family): odd/even number cells keep their distinct resting fills (white vs gray soft) with live-brand labels; previous/next carry the capped corners defined in the token set. Hover / focus washes are runtime 32% mixes of the current brand color.",
  "radio": "Radio control ported 1:1 from the original tokens export (radios.json, brand family). The dot is rendered by the ring alone — no pseudo-elements.",
  "select": "Dropdown trigger ported from the original tokens export (dropdowns.json, brand family): filled square box - no radius or border leaves exist in the token set. The popup stays browser-native; only the closed control is specified by the export.",
  "shadows": "Elevation ported 1:1 from the original tokens export (sys.shadow.*): the six named recipes - button, dropdown, dots, popover, sheet and trigger - each a fixed box-shadow string applied to its own surface. The scrim (overlay.scrim) is the modal backdrop layer, black at 80% opacity, theme-independent; dialog, drawer, sheet and alert dialog all draw it through the same bg-scrim utility.",
  "switch": "Toggle ported from the original tokens export (toggles.json, brand family): outlined track when off, solid live-brand fill when on; knob sizes and edge spacing come straight from the token set. Hover / focus washes are runtime 32% mixes of the current brand color.\n\nDisabled: the whole row (control + label) drops to opacity 0.32 per sys.opacity.disabled with no hover or focus states; on, disabled keeps the knob on the ON side.",
  "tag": "Tag ported 1:1 from the original tokens export (tags.json): one solid container fill per state - default, error, alert and ready - with caption type on each pill. No hover or focus layers are exported for tags, so states stay flat.\n\nDisabled is its own exported state rather than a modifier: same container fill as default with opacity.disabled applied to the whole pill.",
  "tooltip": "Tooltip ported 1:1 from the original tokens export (tooltips.json, brand family): caption type on each variant's fill. Reveal is CSS-only hover / keyboard focus - the token set defines no interaction leaves.",
};